### ISSUE TITLE
Pic symbols out of focus

### ISSUE THREAD

**Issue by cascafico** [systemed/deriviste#1]
When I zoom in, green circles become bigger and bigger, hiding most of Mapnik image.

Chromium 51.0.2704.79 Built on Ubuntu 15.10, running on Ubuntu 16.04 (64-bit)
Firefox 47.0, running on Ubuntu 16.04 (64-bit)

**Comment by mds08011** [comment]
I have the same issue.  The Mapillary overlay does not scale with the map:

![image](https://user-images.githubusercontent.com/8010709/47467319-b4a62680-d7aa-11e8-9e9b-4be2bc675a92.png)

**Comment by cbeddow** [comment]
Fixed by adding raster tile overlay instead of vector
