### ISSUE TITLE
map not visible when theres a lot of imagery

### ISSUE THREAD

**Issue by iamnunocaldeira** [systemed/deriviste#4]
search for "Funchal" and check that due to the ammount of imagery, cant see the map. Was good when i done the quick tutorial when you launched Deriviste.
![imagem](https://user-images.githubusercontent.com/15980854/50252923-8165c980-03e0-11e9-944f-0ec562df1130.png)

**Comment by cbeddow** [comment]
Fixed this with a raster tile implementation that should be visible soon
